# Generated by Django 4.1b1 on 2022-07-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extras", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="mytask",
            options={"ordering": ["-updated", "-created"]},
        ),
        migrations.AlterModelOptions(
            name="spacetask",
            options={"ordering": ["-updated", "-created"]},
        ),
        migrations.RenameField(
            model_name="mytask",
            old_name="title",
            new_name="task",
        ),
        migrations.RenameField(
            model_name="spacetask",
            old_name="title",
            new_name="task",
        ),
        migrations.RemoveField(
            model_name="library",
            name="file",
        ),
        migrations.RemoveField(
            model_name="library",
            name="link",
        ),
        migrations.AddField(
            model_name="mytask",
            name="priority",
            field=models.CharField(
                choices=[("H", "HIGH"), ("M", "MEDIUM"), ("L", "LOW")],
                default="M",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="spacetask",
            name="priority",
            field=models.CharField(
                choices=[("H", "HIGH"), ("M", "MEDIUM"), ("L", "LOW")],
                default="M",
                max_length=15,
            ),
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("file", models.FileField(blank=True, null=True, upload_to="status")),
                ("link", models.URLField()),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("pinned", models.BooleanField(default=False)),
                ("private", models.BooleanField(default=True)),
                ("category", models.ManyToManyField(blank=True, to="extras.category")),
            ],
        ),
        migrations.AddField(
            model_name="library",
            name="books",
            field=models.ManyToManyField(blank=True, to="extras.book"),
        ),
    ]
