# Generated by Django 4.1b1 on 2022-07-14 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extras", "0002_category_alter_mytask_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("created", models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name="book",
            old_name="pinned",
            new_name="saved",
        ),
        migrations.RemoveField(
            model_name="book",
            name="category",
        ),
        migrations.RemoveField(
            model_name="book",
            name="link",
        ),
        migrations.AddField(
            model_name="book",
            name="author",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="description",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="book",
            name="created",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="updated",
            field=models.DateField(auto_now=True),
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.AddField(
            model_name="book",
            name="genre",
            field=models.ManyToManyField(blank=True, to="extras.genre"),
        ),
    ]
