# Generated by Django 4.1b1 on 2022-07-15 00:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("extras", "0003_genre_rename_pinned_book_saved_remove_book_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="library",
            name="books",
            field=models.ManyToManyField(
                blank=True, related_name="lib", to="extras.book"
            ),
        ),
        migrations.AlterField(
            model_name="library",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lib",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="mytask",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
