# Generated by Django 4.1b1 on 2022-07-15 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extras", "0004_alter_library_books_alter_library_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="cover",
            field=models.ImageField(default="", upload_to="cover"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="book",
            name="file",
            field=models.FileField(default="", upload_to="books"),
            preserve_default=False,
        ),
    ]
