# Generated by Django 4.1b1 on 2022-07-15 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extras", "0005_book_cover_alter_book_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="cover",
            field=models.ImageField(blank=True, null=True, upload_to="cover"),
        ),
        migrations.AlterField(
            model_name="book",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="books"),
        ),
    ]
