# Generated by Django 4.1b1 on 2022-07-15 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extras", "0006_alter_book_cover_alter_book_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="private",
        ),
        migrations.AddField(
            model_name="book",
            name="public",
            field=models.BooleanField(default=False),
        ),
    ]
