# Generated by Django 4.1b1 on 2022-07-15 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("extras", "0008_remove_book_genre"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Genre",
        ),
    ]
