# Generated by Django 4.1b1 on 2022-07-15 23:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("extras", "0009_delete_genre"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="creator",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="books",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
