# Generated by Django 4.1b1 on 2022-07-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("extras", "0010_book_creator"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="read",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
