# Generated by Django 4.1b1 on 2022-07-16 15:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("extras", "0011_book_read"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="read",
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name="book",
            name="saved",
        ),
        migrations.AddField(
            model_name="book",
            name="saved",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
