# Generated by Django 4.1b1 on 2022-07-16 15:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("extras", "0012_alter_book_read_remove_book_saved_book_saved"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="saved",
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
