# Generated by Django 4.1b1 on 2022-07-16 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("extras", "0014_alter_book_saved"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="book",
            options={"ordering": ["-updated", "-created"]},
        ),
        migrations.RenameField(
            model_name="book",
            old_name="saved",
            new_name="savers",
        ),
    ]
