# Generated by Django 4.1b1 on 2022-06-28 00:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("peers_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmsg",
            name="chat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chat_msgs",
                to="peers_api.chat",
            ),
        ),
        migrations.AlterField(
            model_name="spacemsg",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="room_msgs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
