# Generated by Django 4.1b1 on 2022-06-29 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peers_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="space",
            name="archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="space",
            name="pinned",
            field=models.BooleanField(default=False),
        ),
    ]
