# Generated by Django 4.1b1 on 2022-06-29 09:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("peers_api", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Status",
            new_name="Story",
        ),
    ]
