# Generated by Django 4.1a1 on 2022-06-20 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("peers_api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organisation",
            name="members",
            field=models.ManyToManyField(
                blank=True, related_name="members", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="friendchat",
            name="receiver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="receiver",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="Friend",
        ),
    ]
