# Generated by Django 4.1a1 on 2022-06-26 05:59

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("peers_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="chat",
            unique_together={("sender", "receiver")},
        ),
    ]
