# Generated by Django 4.1a1 on 2022-06-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peers_api", "0002_organisation_members_alter_friendchat_receiver_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="participants",
            field=models.ManyToManyField(
                blank=True,
                db_column="members",
                null=True,
                related_name="participants",
                to="peers_api.organisation",
            ),
        ),
    ]
