# Generated by Django 4.1b1 on 2022-07-06 00:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("peers_api", "0002_alter_chat_options_alter_space_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="space",
            name="admins",
            field=models.ManyToManyField(
                related_name="space_admins", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
