# Generated by Django 4.1b1 on 2022-07-13 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peers_api", "0002_thread_reply"),
    ]

    operations = [
        migrations.AddField(
            model_name="reply",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="replies/"),
        ),
        migrations.AlterField(
            model_name="reply",
            name="message",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="spacemsg",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="spaces/"),
        ),
    ]
