# Generated by Django 4.1a1 on 2022-06-26 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("peers_api", "0003_rename_body_spacemsg_message_alter_space_topic"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chat",
            options={"ordering": ["-updated", "-created"]},
        ),
        migrations.AlterField(
            model_name="chatmsg",
            name="chat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chatmsg",
                to="peers_api.chat",
            ),
        ),
    ]
