# Generated by Django 4.1b1 on 2022-07-13 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("peers_api", "0003_reply_file_alter_reply_message_alter_spacemsg_file"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Thread",
            new_name="SpaceThread",
        ),
    ]
