# Generated by Django 4.1a1 on 2022-06-20 23:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("peers_api", "0003_alter_room_participants"),
    ]

    operations = [
        migrations.RenameField(
            model_name="topic",
            old_name="name",
            new_name="title",
        ),
        migrations.AlterField(
            model_name="room",
            name="participants",
            field=models.ManyToManyField(
                related_name="participants", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
