# Generated by Django 4.1b1 on 2022-06-28 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peers_api", "0003_chatmsg_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="status",
            name="post",
        ),
        migrations.AddField(
            model_name="status",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="status"),
        ),
        migrations.AlterField(
            model_name="chatmsg",
            name="file",
            field=models.FileField(
                blank=True, null=True, upload_to="chats/% Y/% m/% d/"
            ),
        ),
        migrations.AlterField(
            model_name="spacemsg",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="rooms/"),
        ),
        migrations.AlterField(
            model_name="status",
            name="text",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="text"
            ),
        ),
    ]
