# Generated by Django 4.1a1 on 2022-06-21 00:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("peers_api", "0004_rename_name_topic_title_alter_room_participants"),
    ]

    operations = [
        migrations.AddField(
            model_name="friendchat",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="friendchat",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="topic",
            name="organisation",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="topics",
                to="peers_api.organisation",
            ),
            preserve_default=False,
        ),
    ]
