# Generated by Django 4.1a1 on 2022-06-26 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("peers_api", "0004_alter_chat_options_alter_chatmsg_chat"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="space",
            name="topic",
        ),
        migrations.DeleteModel(
            name="Topic",
        ),
    ]
