# Generated by Django 4.1b1 on 2022-07-14 20:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("peers_api", "0004_rename_thread_spacethread"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="space",
            options={"ordering": ["-pinned", "-updated", "-created"]},
        ),
        migrations.AlterModelOptions(
            name="spacemsg",
            options={"ordering": ["-pinned", "-updated", "-created"]},
        ),
        migrations.AlterField(
            model_name="space",
            name="admins",
            field=models.ManyToManyField(
                blank=True, related_name="isadmin_spaces", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
