# Generated by Django 4.1a1 on 2022-06-21 01:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("peers_api", "0005_friendchat_created_friendchat_updated_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stared",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "stared_friend_msg",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="peers_api.friendchat",
                        verbose_name="Stared Friends Messages",
                    ),
                ),
                (
                    "stared_room_msg",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="peers_api.roomchat",
                        verbose_name="Stared Room Messages",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Users stared messages",
                    ),
                ),
            ],
        ),
    ]
