# Generated by Django 4.1a1 on 2022-06-21 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("peers_api", "0006_stared"),
    ]

    operations = [
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("post", models.FileField(upload_to="")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="status",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="room",
            name="topic",
            field=models.CharField(default="topic", max_length=100),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Topic",
        ),
    ]
