# Generated by Django 4.1a1 on 2022-06-21 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("peers_api", "0008_friendchat_stared_roomchat_stared_delete_stared"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="topic",
        ),
    ]
