# Generated by Django 4.1a1 on 2022-06-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peers_api", "0010_alter_organisation_created"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organisation",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
