# Generated by Django 4.1a1 on 2022-06-21 14:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("peers_api", "0011_alter_organisation_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="status",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="status",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
