# Generated by Django 4.1a1 on 2022-06-22 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("peers_api", "0012_status_created_status_updated"),
    ]

    operations = [
        migrations.AddField(
            model_name="friendchat",
            name="seen",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="roomchat",
            name="seen",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="status",
            name="seen",
            field=models.BooleanField(default=False),
        ),
    ]
