# Generated by Django 4.1a1 on 2022-06-25 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                choices=[
                    (None, "Prefer not to say"),
                    ("male", "Male"),
                    ("female", "Female"),
                ],
                default=None,
                max_length=6,
            ),
        ),
    ]
