# Generated by Django 4.1a1 on 2022-06-27 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[(None, "Prefer not to say"), ("M", "Male"), ("F", "Female")],
                default=None,
                max_length=6,
                null=True,
            ),
        ),
    ]
