# Generated by Django 4.1a1 on 2022-06-15 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_user_otp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="otp",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
