# Generated by Django 4.1a1 on 2022-06-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_alter_profile_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="dept",
            field=models.CharField(default="MTS", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="level",
            field=models.CharField(default="1", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="location",
            field=models.CharField(default="lagos", max_length=100),
            preserve_default=False,
        ),
    ]
