# Generated by Django 4.1a1 on 2022-06-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_profile_dept_profile_level_profile_location"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="dept",
            new_name="course",
        ),
        migrations.AddField(
            model_name="profile",
            name="department",
            field=models.CharField(default="u", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="profile",
            name="institution",
            field=models.CharField(default="o", max_length=100),
            preserve_default=False,
        ),
    ]
