# Generated by Django 4.1a1 on 2022-06-20 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0008_rename_dept_profile_course_profile_department_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female"), ("P", "Prefer not to say")],
                default="P",
                max_length=6,
            ),
        ),
    ]
